In [4]:
from PIL import Image

In [5]:
from keras.applications.vgg16 import preprocess_input

In [6]:
import base64

In [7]:
from io import BytesIO

In [8]:
import json

In [9]:
import  random

In [10]:
import cv2

In [11]:
from keras.models import load_model

In [12]:
import numpy as np

In [13]:
from keras.preprocessing import image

In [14]:
model = load_model('face_determination_model.h5')

In [15]:
#loading cascades

In [16]:
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [17]:
def face_extractor(img):
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    if faces is ():
        return None
    #crop all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img, (x,y), (x+w,y+h), (0,255,255), 2)
        cropped_face = img[y:y+h,x:x+w]
    return cropped_face    

<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\s8908\AppData\Local\Temp\ipykernel_8608\1933924516.py:3: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [18]:
#face recognition with webcam

In [19]:
video_capture = cv2.VideoCapture(0)

In [20]:
while True:
    _, frame = video_capture.read()
    face = face_extractor(frame)
    if type(face) is np.ndarray:
        face = cv2.resize(face, (244,244))
        im = Image.fromarray(face, 'RGB')
        img_array = np.array(im)
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)
        name = "None matching"
        if (pred[0][1]>0.5):
            name = 'Saurabh-R'
            cv2.putText(frame, name, (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,255,0), 2) 
        else:
            cv2.putText(frame,"No face found", (50,50), cv2.FONT_HERSHEY_DUPLEX, 1 ,(0,255,0), 2)
        cv2.imshow('face-recognition',frame)
    if cv2.waitKey(1) & 0XFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

1/1 [==============================] - 0s 421ms/step
[[1.000000e+00 3.936954e-37]]
1/1 [==============================] - 0s 163ms/step
[[9.995066e-01 4.933564e-04]]
1/1 [==============================] - 0s 147ms/step
[[1.000000e+00 7.359268e-22]]
1/1 [==============================] - 0s 143ms/step
[[1.1418921e-15 1.0000000e+00]]
1/1 [==============================] - 0s 175ms/step
[[1.000000e+00 9.407736e-13]]
1/1 [==============================] - 0s 146ms/step
[[1.0000000e+00 1.0014965e-30]]
1/1 [==============================] - 0s 142ms/step
[[9.998542e-01 1.457733e-04]]
1/1 [==============================] - 0s 141ms/step
[[3.9281393e-19 1.0000000e+00]]
1/1 [==============================] - 0s 157ms/step
[[9.99896765e-01 1.03273436e-04]]
1/1 [==============================] - 0s 141ms/step
[[1.8458797e-17 1.0000000e+00]]
1/1 [==============================] - 0s 143ms/step
[[1.000000e+00 3.485702e-21]]
1/1 [==============================] - 0s 167ms/step
[[9.999547e-01 4.53365

In [21]:
cv2.__version__

'4.8.0'